from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://www.selenium.dev/selenium/web/web-form.html")
time.sleep(2)
print("\n--- Dynamic XPath Examples ---")
heading = driver.find_element(By.XPATH, "//h1[text()='Web form']")
print("Found heading:", heading.text)
time.sleep(2)
text_box = driver.find_element(By.XPATH, "//input[contains(@id,'my-text')]")
text_box.send_keys("Dynamic XPath Example")
print("Typed text using contains()")
time.sleep(2)
password_box = driver.find_element(By.XPATH, "//input[@type='password' and @name='my-password']")
password_box.send_keys("MySecret123")
print("Filled password box using AND")
time.sleep(2)
email_field = driver.find_element(By.XPATH, "//input[@name='my-password' or @id='my-text-id']")
print("Located element using OR condition")
time.sleep(2)
dropdown = driver.find_element(By.XPATH, "//select[starts-with(@name,'my-')]")
dropdown.click()
print("Clicked dropdown using starts-with()")
button = driver.find_element(By.XPATH, "//button[contains(text(),'Submit')]")
print("Found button with contains(text()):", button.text)
time.sleep(2)
heading2 = driver.find_element(By.XPATH, "//h1[starts-with(text(),'Web')]")
print("Found heading using starts-with(text()):", heading2.text)
time.sleep(2)
driver.quit()
